# install-watchdog-startup.ps1
# Install persistent Watchdog via shell:startup (no admin rights required)
#
# How it works:
#   shell:startup folder contains shortcuts that auto-run on user logon.
#   We drop a .vbs launcher (silent VBScript) into shell:startup.
#   VBScript spawns the PS1 watchdog in a hidden window.
#   PS1 loops forever, checking every 5min.
#   No admin rights, no Windows Task Scheduler, no NSSM, no service install.
#
# Usage (any user, no admin):
#   powershell -NoProfile -ExecutionPolicy Bypass -File F:\aitoptools\scripts\install-watchdog-startup.ps1
#
# Verify (any user):
#   Test-Path "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\aitoptools-mavis-watchdog.vbs"
#   Get-Process powershell | Where-Object { $_.CommandLine -like '*watchdog-loop.ps1*' }
#
# Uninstall:
#   powershell -NoProfile -ExecutionPolicy Bypass -File F:\aitoptools\scripts\uninstall-watchdog-startup.ps1

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$SCRIPT_DIR = Split-Path -Parent $MyInvocation.MyCommand.Definition
$PROJECT_ROOT = Split-Path -Parent $SCRIPT_DIR
$PS1_PATH = Join-Path $SCRIPT_DIR 'watchdog-loop.ps1'

# shell:startup path (per-user, no admin required)
$STARTUP_DIR = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup'
$VBS_PATH = Join-Path $STARTUP_DIR 'aitoptools-mavis-watchdog.vbs'

# 1. Validate PS1 exists
if (-not (Test-Path $PS1_PATH)) {
    Write-Host "ERROR: $PS1_PATH not found" -ForegroundColor Red
    exit 1
}

# 2. Write VBS launcher (silent, hidden window)
#    VBScript uses WScript.Sleep (native Win32) - more stable than PowerShell Start-Sleep
#    in hidden window + long interval scenario (PowerShell 7/31 跑了 1 tick 后被 kill)
$VBS_SCRIPT = Join-Path $SCRIPT_DIR 'watchdog-loop-vbs.vbs'
if (-not (Test-Path $VBS_SCRIPT)) {
    Write-Host "ERROR: $VBS_SCRIPT not found" -ForegroundColor Red
    exit 1
}

$vbsContent = @"
' aitoptools-mavis-watchdog.vbs
' Auto-generated by install-watchdog-startup.ps1 (2026-07-31 v2)
' Silent launcher for mavis cron daemon watchdog (VBScript - more stable than PowerShell)
' Triggered on user logon via shell:startup

Set WshShell = CreateObject("WScript.Shell")
WshShell.Run "wscript.exe ""$VBS_SCRIPT""", 0, False
"@

Set-Content -Path $VBS_PATH -Value $vbsContent -Encoding UTF8 -Force
Write-Host "VBS launcher written: $VBS_PATH" -ForegroundColor Green
Write-Host "  -> Spawns VBScript: $VBS_SCRIPT" -ForegroundColor Green

# 3. Start the watchdog right now (in case user is already logged in)
$runningWatchdog = Get-Process powershell -ErrorAction SilentlyContinue | Where-Object {
    $_.CommandLine -like "*watchdog-loop.ps1*"
}
if ($runningWatchdog) {
    Write-Host "Watchdog already running (PID: $($runningWatchdog.Id -join ', '))" -ForegroundColor Yellow
} else {
    try {
        Start-Process powershell.exe -ArgumentList @(
            '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', "`"$PS1_PATH`""
        ) -WindowStyle Hidden
        Write-Host "Watchdog started (will check every 5min)" -ForegroundColor Green
    } catch {
        Write-Host "WARN: Could not start watchdog right now: $($_.Exception.Message)" -ForegroundColor Yellow
        Write-Host "It will auto-start on next user logon via shell:startup" -ForegroundColor Yellow
    }
}

# 4. Summary
Write-Host ""
Write-Host "=== Installation Complete ===" -ForegroundColor Cyan
Write-Host "  PS1 path:    $PS1_PATH"
Write-Host "  VBS path:    $VBS_PATH"
Write-Host "  Trigger:     User logon (shell:startup) + immediate (if logged in)"
Write-Host "  Interval:    5 min"
Write-Host "  Action:      Check MiniMax Code, start if not running, log to .hermes/logs/watchdog-loop-*.log"
Write-Host ""
Write-Host "Verify status (any time, no admin):" -ForegroundColor Yellow
Write-Host "  Test-Path '$VBS_PATH'"
Write-Host "  Get-Process powershell | Where-Object { `$_.CommandLine -like '*watchdog-loop.ps1*' }"
Write-Host "  Get-Content '$((Join-Path (Join-Path $PROJECT_ROOT '.hermes') 'logs'))\watchdog-loop-'`$(Get-Date -Format 'yyyy-MM-dd')'.log'"
Write-Host ""
Write-Host "Uninstall:" -ForegroundColor Yellow
Write-Host "  powershell -NoProfile -ExecutionPolicy Bypass -File $SCRIPT_DIR\uninstall-watchdog-startup.ps1"
